module.exports = {
  extends: require.resolve('./recommended.js'),

  rules: {
    // Rules that are only necessary without prettier
    'quotes': ['error', 'single', { 'allowTemplateLiterals': true }],
    'no-tabs': 'error',
    'eol-last': ['error', 'always'],
    'comma-dangle': ['error', {
      'arrays': 'never',
      'objects': 'always-multiline',
      'imports': 'always-multiline',
      'exports': 'always-multiline',
      'functions': 'ignore',
    }],
    'no-multi-spaces': ['error', { ignoreEOLComments: true }],
    'block-spacing': 'error',
    'brace-style': 'error',
    'comma-spacing': ['error', { 'before': false,
      'after': true }],
    'comma-style': 'error',
    'func-call-spacing': 'error',
    'function-paren-newline': ['error', 'consistent'],
    'indent': ['error', 2],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'new-parens': 'error',
    'newline-per-chained-call': 'error',
    'no-whitespace-before-property': 'error',
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ["error", { "allowAllPropertiesOnSameLine": true }],
    'semi': 'error',
    'semi-style': 'error',
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': 'error',
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'spaced-comment': 'error',
    'switch-colon-spacing': 'error',
    'space-before-blocks': 'error',
  },

};
